---
- name: Setup Display Manager
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Install Packages
      apt:
        update_cache: true
        pkg:
          - lightdm
          - unclutter
          - libx11-dev
          - x11-utils
          - xinput

    - name: Install snap packages for chromium
      snap:
        name:
          - chromium

    - name: create xsessions directory
      file: path=/usr/share/xsessions/ state=directory

    - name: Copy kiosk.desktop
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/display-setup/kiosk.desktop"
        dest: /usr/share/xsessions/kiosk.desktop
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: configure standby in kiosk.desktop Exec
      community.general.ini_file:
        path: /usr/share/xsessions/kiosk.desktop
        section: Desktop Entry
        option: Exec
        value: "/home/{{ ansible_user }}/standby-screen/standby.py"
        backup: false
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: configure standby in kiosk.desktop TryExec
      community.general.ini_file:
        path: /usr/share/xsessions/kiosk.desktop
        section: Desktop Entry
        option: TryExec
        value: "/home/{{ ansible_user }}/standby-screen/standby.py"
        backup: false
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Set display manager for {{ ansible_user }} user
      ini_file:
        path: "/home/{{ ansible_user }}/.dmrc"
        section: Desktop
        option: Session
        value: kiosk
        backup: false
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Copy {{ ansible_user }} xhost.sh
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/display-setup/xhost.sh"
        dest: "/home/{{ ansible_user }}/xhost.sh"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Set lightdm kiosk config
      ini_file:
        path: /usr/share/lightdm/lightdm.conf.d/99-kiosk.conf
        section: "Seat:*"
        option: user-session
        # session name NOT user name
        value: kiosk
        backup: false
        mode: "0644"

    - name: Set lightdm to auto login at startup 1/3
      ini_file:
        path: /etc/lightdm/lightdm.conf
        section: "Seat:*"
        option: autologin-guest
        value: false
        backup: false

    - name: Set lightdm to auto login at startup 2/3
      ini_file:
        path: /etc/lightdm/lightdm.conf
        section: "Seat:*"
        option: autologin-user
        value: "{{ ansible_user }}"
        backup: false

    - name: Set lightdm to auto login at startup 3/3
      ini_file:
        path: /etc/lightdm/lightdm.conf
        section: "Seat:*"
        option: autologin-user-timeout
        value: 0
        backup: false

    - name: Set lightdm to share its xsession with other users
      ini_file:
        path: /etc/lightdm/lightdm.conf
        section: "SeatDefaults"
        option: display-setup-script
        value: /home/{{ ansible_user }}/xhost.sh
        backup: false

    - name: Turn off the cursor
      ini_file:
        path: /etc/lightdm/lightdm.conf
        section: "SeatDefaults"
        option: xserver-command
        value: X -nocursor
        backup: false

    - name: set display manager to lightdm
      lineinfile:
        state: present
        dest: /etc/X11/default-display-manager
        line: /usr/sbin/lightdm

    - name: set display manager to NOT be gdm3
      lineinfile:
        state: absent
        dest: /etc/X11/default-display-manager
        line: /usr/sbin/gdm3

    - name: run dpkg-reconfigure for lightdm
      shell: dpkg-reconfigure --frontend noninteractive lightdm

    - name: Creates "standby-screen" directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/standby-screen
        state: directory

    - name: Copy standby script
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../standby-screen/standby.py"
        dest: /home/{{ ansible_user }}/standby-screen/standby.py
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0775"

    - name: Copy standby theme
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../standby-screen/theme.css"
        dest: /home/{{ ansible_user }}/standby-screen/theme.css
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0664"
