---
- hosts: all

- name: Basic Shell Setup
  import_playbook: shell-setup.yaml

- name: Setup Display
  import_playbook: display-setup.yaml

- name: Reboot
  hosts: all
  tasks:
    - name: reboot in 1 minute
      become: true
      become_method: sudo
      shell: shutdown -r 1
